"""Initial migration

Revision ID: 2c6cf981edbc
Revises: 
Create Date: 2023-02-25 01:00:29.873155

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import table

from src.core.settings import settings
from src.services.users import UsersService

# revision identifiers, used by Alembic.
revision = '2c6cf981edbc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tanks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('max_capacity', sa.Float(), nullable=False),
    sa.Column('current_capacity', sa.Float(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tanks_product_id'), 'tanks', ['product_id'], unique=False)
    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mass', sa.Float(), nullable=False),
    sa.Column('date_start', sa.DateTime(), nullable=False),
    sa.Column('date_end', sa.DateTime(), nullable=False),
    sa.Column('tank_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operations_product_id'), 'operations', ['product_id'], unique=False)
    op.create_index(op.f('ix_operations_tank_id'), 'operations', ['tank_id'], unique=False)

    users = table('users',
                  sa.Column('id', sa.Integer(), nullable=False, primary_key=True, autoincrement=True),
                  sa.Column('username', sa.String(), nullable=False),
                  sa.Column('password_hash', sa.String(), nullable=False),
                  sa.Column('role', sa.String(), nullable=True),
                  sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                  sa.Column('created_by', sa.Integer(), nullable=False),
                  sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                  sa.Column('modified_by', sa.Integer(), nullable=False),
    )

    op.bulk_insert(users,
        [
            {
            'username': settings.admin_username,
            'password_hash': UsersService().hash_password(settings.admin_password),
            'role': 'admin',
            'created_by': 1,
            'modified_by': 1,
            }
        ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operations_tank_id'), table_name='operations')
    op.drop_index(op.f('ix_operations_product_id'), table_name='operations')
    op.drop_table('operations')
    op.drop_index(op.f('ix_tanks_product_id'), table_name='tanks')
    op.drop_table('tanks')
    op.drop_table('products')
    op.drop_table('users')
    # ### end Alembic commands ###
